version: '3.7'
services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: stock
        ports:
            - 3306:3306

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - '.:/usr/src/app'
        depends_on:
            - db

    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - './public:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - 80:80
        depends_on:
            - php

    adminer:
        image: adminer
        restart: on-failure
        ports:
            - 8080:8080